apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      restartPolicy: Always
      containers:
      - name: db
        image: postgres:9.4
        ports:
        - containerPort: {{ .Values.postgres_port }}
        env:
        - name: BUILDBOT_DB_URL
          value: "postgresql+psycopg2://{{ .Values.postres_user }}:{{ .Values.postgres_password }}@db/{{ .Values.postgres_db }}"
        - name: POSTGRES_DB
          value: {{ .Values.postgres_db }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres_password }}
        - name: POSTGRES_USER
          value: {{ .Values.postres_user }}
