apiVersion: v1
kind: Service
metadata:
  name: buildbot
  labels:
    app: buildbot
spec:
  selector:
    app: buildbot
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: "9989"
    port: 9989
    protocol: TCP
    targetPort: 9989
