apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
  - name: "{{ .Values.postgres_port }}"
    port: {{ .Values.postgres_port }}
    protocol: TCP
    targetPort: {{ .Values.postgres_port }}
  selector:
    app: db
  type: ClusterIP
