

buildbot_config_url: ""
buildbot_web_url: "http://localhost:8080/"
buildbot_mq_debug: "info"
postgres_db: "buildbot"
postgres_password: "change_me"
postres_user: "buildbot"
postgres_port: 5432
workerLogin: "worker"
workerPassword: "change_me"
master_image: olafradicke/alternativ_buildbot_master:v2.7.0r8
master_replicas: 2
wortkerTypes:
  "root-worker":
    image: olafradicke/alternativ_buildbot_root_worker:latest
    replicas: 1
  "minimal-worker":
    image: olafradicke/alternativ_buildbot_worker:latest
    replicas: 2